### ISSUE TITLE
How do i make it work in Safari?

### ISSUE THREAD

**Issue by frozeman** [ecwyne/meteor-polymer#1]
The platform.js doesn't seem to do its job

**Comment by bangonkali** [comment]
In order to load custom html before any meteor related code use this pattern on your server:

```
var http = Npm.require('http');

var originalWrite = http.OutgoingMessage.prototype.write;
http.OutgoingMessage.prototype.write = function(chunk, encoding) {

  if (typeof chunk == 'string' || chunk instanceof String) {
    
	// Add web components & polymer on top of the website.
	var polymer = '\t<script type="text/javascript" src="/bower_components/webcomponentsjs/webcomponents.js"></script>\n';
    polymer += '\t<link rel="import" href="/bower_components/polymer/polymer.html">\n';
    chunk = chunk.replace('<head>', '<head>\n' + polymer);
	
	// Add single tag attributes to body. this returns an error if done within meteor.
    chunk = chunk.replace('<body>', '<body unresolved fullbleed vertical layout>');

    this._injected = true;
  }

  originalWrite.call(this, chunk, encoding);
};
```

Code above is patterned from [meteor-inject](https://github.com/meteorhacks/meteor-inject-initial/blob/master/lib/inject-core.js#L5) and [inject-data](https://github.com/meteorhacks/inject-data/blob/master/lib/server.js#L25).

However, on my end, template events (such as button clicks) are still not working on Firefox and Internet Explorer 11. I have not tested on Safari yet though. My [prototype] (https://www.acomsys.net) only  works on chrome.

**Comment by bangonkali** [comment]
Ok, with regards to the 'events' not triggering, this [one](https://github.com/Differential/polymer-demo/issues/6#issuecomment-70098242) solved my problems.
